name: CICD tests

on: 
  push:
    paths:
      - 'Modules/M08_CICD/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install Dependencies
      run: |
        pip install pandas
        pip install pytest
        pip install -e .

    - name: PyTest
      run: |
        pytest -v Modules/M08_CICD/tests/test.py
          
